language: java
install: mvn install -DskipTests=true
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
before_install:
  - pip install --user codecov

  # Code coverage for codecy
  - curl -sL http://bit.ly/jpm4j >jpm4j.jar
  - java -jar jpm4j.jar --user init
  - ${HOME}/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly
  #  - curl https://www.jpm4j.org/install/script | sh
  #  - jpm install com.codacy:codacy-coverage-reporter:assembly
after_success:
  - codecov

  # Code coverage for codecy
  # - codacy-coverage-reporter -l Java -r coverage.xml
  - ${HOME}/jpm/bin/codacy-coverage-reporter -l Java -r coverage.xml
