comment:
  layout: header, changes, diff
coverage:
  ignore:
  - src/main/java/io/github/seleniumquery/by/firstgen/filter/*
  - src/main/java/io/github/seleniumquery/browser/BrowserFunctionsWithDeprecatedFunctions.java
  - src/main/java/io/github/seleniumquery/browser/driver/builders/ChromeDriverBuilder.java
  - src/main/java/io/github/seleniumquery/browser/driver/builders/FirefoxDriverBuilder.java
  - src/main/java/io/github/seleniumquery/browser/driver/builders/InternetExplorerDriverBuilder.java
  status:
    patch: false
    
