version: 2

jobs:
    build:
        docker:
        - image: gradle:jdk8
        steps:
        - checkout
        - restore_cache:
              keys:
              - gradle-{{ checksum "build.gradle" }}
        - run:
              command: ./gradlew check jacocoTestReport && bash <(curl -s https://codecov.io/bash)
        - save_cache:
              paths:
              - ~/.gradle
              key: gradle-{{ checksum "build.gradle" }}
        - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
              path: build/reports
              destination: reports
        - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
              path: build/test-results
        # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
